# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20241219-175208-persistent-minute

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: ru

pipeline:
  - name: WhitespaceTokenizer
  - name: LexicalSyntacticFeaturizer # Токенизатор, разделяющий текст по пробелам
  - name: "LanguageModelFeaturizer"
    model_name: "bert"                       # Модель BERT для русского языка
    model_weights: "bert-base-cased"          # Весы модели BERT
    cache_dir: null
  - name: DIETClassifier                   # классификатор намерений и сущностей
    epochs: 200                            # число эпох обучения

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: RulePolicy
